- name: Backend installations
  hosts: backend
  become: yes
  tasks:
    - name: Disable default nodejs version(16)
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable nodejs version(20)
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Installing nodejs
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Checking user expense exists
      ansible.builtin.command: id expense
      register: output
      ignore_errors: true

    - name: Print
      ansible.builtin.debug:
        msg: "{{ output }}"

    - name: Adding user expense
      ansible.builtin.shell: useradd expense
      when: output.failed is true

    - name: Making directory app
      ansible.builtin.command: mkdir -p /app

    - name: Delete previous downloaded code
      ansible.builtin.command: rm -f /tmp/backend.zip

    - name: Downloading source code
      ansible.builtin.shell: curl -p -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip

    - name: Delete previous code in /app
      ansible.builtin.shell: rm -rf /app/*

    - name: Changing directiory to app
      ansible.builtin.command: cd /app

    - name: Unzip source code to /app
      ansible.builtin.command: unzip /tmp/backend.zip

    - name: Changing directiory to app
      ansible.builtin.command: cd /app

    - name: Installing backend packages from source code
      ansible.builtin.shell: npm install

    - name: Creating backend service
      ansible.builtin.shell: cp -p /home/ec2-user/expense-ansible/backend.service /etc/systemd/system/backend.service

    - name: Daemon Reload
      ansible.builtin.command: systemctl daemon-reload

    - name: Starting and enabling backend
      ansible.builtin.service:
        name: backend
        state: started
        enabled: yes

    - name: Install mysql
      ansible.builtin.package:
        name: mysql
        state: present

    - name: Loading db schema
      ansible.builtin.command: mysql -h 3.87.204.197 -uroot -pExpenseApp@1 < /app/schema/backend.sql

    - name: Restarting backend
      ansible.builtin.service:
        name: backend
        state: restarted
