- name: Install Mysql-server
  hosts: mysql
  become: yes
  tasks:
    - name: Installing
      ansible.builtin.package:
        name: mysql-server
        state: present
    - name: Starting and enabling
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Setting password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
